<a href="https://colab.research.google.com/github/dewiginting123/MachineLearning/blob/main/WEEK%2010/Week_10_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch A

In [1]:
%matplotlib inline
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [2]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



1. TENSORS

In [3]:
import torch
import numpy as np

In [4]:
#1. Directly from data

#Tensors can be created directly from data. The data type is automatically inferred.

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
#2. From a NumPy array

#Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"np array: \n {np_array} \n")
print(f"tensor  : \n {x_np} \n")

np array: 
 [[1 2]
 [3 4]] 

tensor  : 
 tensor([[1, 2],
        [3, 4]]) 



In [6]:
#3. From another tensor:
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2361, 0.5330],
        [0.9002, 0.8089]]) 



In [7]:
#4. With random or constant values:
# shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3428, 0.8186, 0.6795],
        [0.1878, 0.1276, 0.4071]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Operations on Tensors

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [10]:
# Standard numpy-like indexing and slicing:

tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
#Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.
#See also torch.stack, another tensor joining op that is subtly different from torch.cat.

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1 : {y1}")
print(f"y2 : {y2}")
print(f"y3 : {y3}")

y1 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [13]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
#Single-element tensors If you have a one-element tensor,
#for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [15]:
#In-place operations Operations that store the result into the operand are called in-place. 
#They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Tensor to NumPy array

In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
#A change in the tensor reflects in the NumPy array.

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [18]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [19]:
#Changes in the NumPy array reflects in the tensor.

np.add(n, 1, out=n)

print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Pytorch B

1. DATASETS & DATALOADERS

In [20]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

1. TRANSFORMS

In [21]:
ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)

1. BUILD THE NEURAL NETWORK

In [22]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

Get Device for Training

In [23]:
#We want to be able to train our model on a hardware accelerator like the GPU, if it is available. 
#Let’s check to see if torch.cuda is available, else we continue to use the CPU.
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device')

Using cpu device


Define the Class

In [24]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [25]:
# We create an instance of NeuralNetwork, and move it to the device, and print its structure.

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [26]:
#To use the model, we pass it the input data. This executes the model’s forward, along with some background operations. 
#Do not call model.forward() directly! Calling the model on the input returns a 10-dimensional tensor with raw predicted values for each class.
#We get the prediction probabilities by passing it through an instance of the nn.Softmax module.



# Executes the model
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([5])


Model Layers

In [27]:
#break down the layers in the FashionMNIST model. 
#To illustrate it, we will take a sample minibatch of 3 images of size 28x28 and see what happens to it as we pass it through the network.


input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


nn.Flatten

In [28]:
#initialize the nn.Flatten layer to convert each 2D 28x28 image 
#into a contiguous array of 784 pixel values ( the minibatch dimension (at dim=0) is maintained).


flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


nn.Linear

In [29]:
#The linear layer is a module that applies a linear transformation on the input using its stored weights and biases.


layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


nn.ReLU

In [30]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 2.0096e-01, -1.8814e-01, -5.3473e-01,  4.0277e-02,  2.2951e-01,
          4.5970e-01,  2.8506e-01, -1.9956e-01,  1.8704e-01, -1.9464e-01,
          4.4014e-02,  7.7666e-01,  4.5639e-02,  3.5431e-02,  2.0687e-01,
          3.2575e-01,  1.6018e-01,  1.0862e+00, -4.4872e-01,  7.2221e-01],
        [-2.5802e-01,  6.2821e-01, -2.7585e-01,  1.0452e-01,  5.8321e-02,
          4.4933e-01,  2.6310e-01, -2.3253e-01, -1.5975e-01, -3.5432e-01,
          2.9776e-01,  9.9692e-01, -1.2324e-01,  1.6502e-01,  1.7372e-01,
          3.3345e-01,  1.8184e-01,  9.0918e-01, -4.6940e-01,  8.1420e-01],
        [-2.5892e-01,  5.6261e-01, -5.0699e-01,  2.2228e-02, -5.4831e-03,
          4.6374e-01,  1.8452e-01, -1.8900e-02,  9.2085e-02, -2.7508e-01,
          3.7480e-01,  8.5162e-01, -3.1539e-01,  1.3800e-01,  5.4112e-02,
          1.7908e-01, -9.0672e-04,  1.2263e+00,  6.9874e-02,  6.9161e-01]],
       grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.2010, 0.0000, 0.0000, 0.0403, 0.2295,

In [31]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

nn.Softmax

In [32]:
#The last linear layer of the neural network returns logits - raw values in [-infty, infty] - which are passed to the nn.Softmax module. 
#The logits are scaled to values [0, 1] representing the model’s predicted probabilities for each class. 
#dim parameter indicates the dimension along which the values must sum to 1.


softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

Model Paraeters

In [33]:
#Subclassing nn.Module automatically tracks all fields defined inside your model object, 
#and makes all parameters accessible using your model’s parameters() or named_parameters() methods.
#In this example, we iterate over each parameter, and print its size and a preview of its values.


print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure:  NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
) 


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0329, -0.0095, -0.0133,  ...,  0.0157, -0.0294, -0.0332],
        [ 0.0230, -0.0082, -0.0074,  ...,  0.0243, -0.0342,  0.0246]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([ 0.0160, -0.0266], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0126, -0.0119,  0.0262,  ..., -0.0018, -0.0098,  0.0372],
        [-0.0037, -0.0192, -0.0206,  ..., -0.0409, -0.0272,  0.0019]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias 

1. AUTOMATIC DIFFERENTIATION WITH TORCH.AUTOGRAD

In [34]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

Tensors, Functions and Computational graph

In [35]:
print('Gradient function for z =', z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x7f633507d190>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7f63f53d6f50>


Computing Gradients

In [36]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0426, 0.3110, 0.1942],
        [0.0426, 0.3110, 0.1942],
        [0.0426, 0.3110, 0.1942],
        [0.0426, 0.3110, 0.1942],
        [0.0426, 0.3110, 0.1942]])
tensor([0.0426, 0.3110, 0.1942])


Disabling Gradient Tracking

In [37]:
#By default, all tensors with requires_grad=True are tracking their computational history and support gradient computation. 
#We can stop tracking computations by surrounding our computation code with torch.no_grad() block:


z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [38]:
# Another way to achieve the same result is to use the detach() method on the tensor:

z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


6. OPTIMIZING MODEL PARAMETERS

In [39]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

train_dataloader = DataLoader(training_data, batch_size=64)
test_dataloader = DataLoader(test_data, batch_size=64)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork()

In [40]:
learning_rate = 1e-3
batch_size = 64
epochs = 5

Optimization Loop

Loss Function

In [41]:
# Initialize the loss function
loss_fn = nn.CrossEntropyLoss()

Optimizer

In [42]:
#We initialize the optimizer by registering the model’s parameters that need to be trained, and passing in the learning rate hyperparameter.

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [43]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [44]:
#We initialize the loss function and optimizer, and pass it to train_loop and test_loop. 
#Feel free to increase the number of epochs to track the model’s improving performance.

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.290251  [    0/60000]
loss: 2.284245  [ 6400/60000]
loss: 2.268245  [12800/60000]
loss: 2.266919  [19200/60000]
loss: 2.245341  [25600/60000]
loss: 2.213518  [32000/60000]
loss: 2.225518  [38400/60000]
loss: 2.191432  [44800/60000]
loss: 2.188794  [51200/60000]
loss: 2.153340  [57600/60000]
Test Error: 
 Accuracy: 38.0%, Avg loss: 2.153931 

Epoch 2
-------------------------------
loss: 2.164574  [    0/60000]
loss: 2.157778  [ 6400/60000]
loss: 2.104718  [12800/60000]
loss: 2.121161  [19200/60000]
loss: 2.063873  [25600/60000]
loss: 2.003316  [32000/60000]
loss: 2.031186  [38400/60000]
loss: 1.957454  [44800/60000]
loss: 1.964087  [51200/60000]
loss: 1.877849  [57600/60000]
Test Error: 
 Accuracy: 56.9%, Avg loss: 1.887535 

Epoch 3
-------------------------------
loss: 1.926471  [    0/60000]
loss: 1.893118  [ 6400/60000]
loss: 1.786610  [12800/60000]
loss: 1.820599  [19200/60000]
loss: 1.695918  [25600/60000]
loss: 1.656953  [32000/600